# RAG -Search


- [Introduction to information Retrieval](https://nlp.stanford.edu/IR-book/information-retrieval-book.html)


Install packages


In [2]:
!uv pip install -q \
    pandas==2.3.2 \
    pandas-stubs==2.3.2.250827 \
    numpy==2.3.2 \
    matplotlib==3.10.6 \
    scikit-learn==1.7.1 \
    requests==2.32.5

Import packages


In [ ]:
import numpy as np
import pandas as pd
import requests
from sklearn.decomposition import NMF, TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Get documents


In [ ]:
docs_url = "https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json"
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course["course"]
    for doc in course["documents"]:
        doc["course"] = course_name
        documents.append(doc)

documents[0]

{'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
 'section': 'General course-related questions',
 'question': 'Course - When will the course start?',
 'course': 'data-engineering-zoomcamp'}

Create a DataFrame


In [ ]:
df = pd.DataFrame(documents, columns=["course", "section", "question", "text"])
df.head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

Vector spaces

- Turn docs into vectors
- Term-document-matrix:
  - rows: documents
  - columns: words/tokens
- Bag of words: counts occurrences of each word in each document

| Document | word1 | word2 | word3 |
| -------- | ----- | ----- | ----- |
| Doc1     | 1     | 0     | 2     |
| Doc2     | 0     | 3     | 1     |


In [ ]:
cv = CountVectorizer(min_df=5, stop_words="english")  # Min Document Frequency
X = cv.fit_transform(df.text)
column_names = cv.get_feature_names_out()
column_names

array(['01', '02', '03', ..., 'youtube', 'zip', 'zoomcamp'],
      shape=(1333,), dtype=object)

Number of distinct tokens


In [ ]:
cv.get_feature_names_out().shape

(1333,)

Tokens by occurrences


In [ ]:
df_docs = pd.DataFrame(X.toarray(), columns=column_names)
df_docs.head()

01  02  03  04  05  06  09  10  100  11  ...  y_val  yaml  year  yellow  \
0   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
1   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
2   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
3   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
4   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   

   yellow_tripdata_2021  yes  yml  youtube  zip  zoomcamp  
0                     0    0    0        0    0         0  
1                     0    0    0        0    0         1  
2                     0    1    0        0    0         0  
3                     0    0    0        0    0         0  
4                     0    0    0        0    0         0  

[5 rows x 1333 columns]

Tokens by importance


In [ ]:
tv = TfidfVectorizer(min_df=5, stop_words="english")  # Min Document Frequency
X = tv.fit_transform(df.text)
column_names = tv.get_feature_names_out()
column_names
df_docs = pd.DataFrame(X.toarray(), columns=column_names)
df_docs.head()

01   02   03   04   05   06   09   10  100   11  ...  y_val  yaml  year  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   0.0   

   yellow  yellow_tripdata_2021       yes  yml  youtube  zip  zoomcamp  
0     0.0                   0.0  0.000000  0.0      0.0  0.0  0.000000  
1     0.0                   0.0  0.000000  0.0      0.0  0.0  0.428961  
2     0.0                   0.0  0.279891  0.0      0.0  0.0  0.000000  
3     0.0                   0.0  0.000000  0.0      0.0  0.0  0.000000  
4     0.0                   0.0  0.000000  0.0      0.0  0.0  0.000000  

[5 rows x 1333 columns]

## Text Search


In [ ]:
query = "I just discovered the course, is it too late to join?"

q = cv.transform([query])
q.toarray()

array([[0, 0, 0, ..., 0, 0, 0]], shape=(1, 1333))

Relevant documents


In [ ]:
score = cosine_similarity(X, q).flatten()
np.argsort(score)[-5:]

array([ 27, 449, 440,  22,   0])

Document example


In [ ]:
df.iloc[0].text

"The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel."

Creating matrices


In [ ]:
fields = ["section", "question", "text"]

matrices = {}
vectorizers = {}

for f in fields:
    cv = TfidfVectorizer(stop_words="english", min_df=5)
    X = cv.fit_transform(df[f])
    matrices[f] = X
    vectorizers[f] = cv

Scoring


In [ ]:
n = len(df)
score = np.zeros(n)
boosts = {"question": 3}

for f in fields:
    q = vectorizers[f].transform([query])
    X = matrices[f]

    f_score = cosine_similarity(X, q).flatten()
    boost = boosts.get(f, 1.0)
    score = score + boost * f_score

Filtering


In [ ]:
filters = {"course": "data-engineering-zoomcamp"}

for field, value in filters.items():
    mask = (df[field] == value).values
    score = score * mask

Getting most relevant documents


In [ ]:
idx = np.argsort(score)[-5:][::-1]
df.iloc[idx]

course                           section  \
7   data-engineering-zoomcamp  General course-related questions   
0   data-engineering-zoomcamp  General course-related questions   
1   data-engineering-zoomcamp  General course-related questions   
34  data-engineering-zoomcamp  General course-related questions   
4   data-engineering-zoomcamp  General course-related questions   

                                             question  \
7   Course - Can I follow the course after it fini...   
0                Course - When will the course start?   
1   Course - What are the prerequisites for this c...   
34               How can we contribute to the course?   
4    Course - What can I do before the course starts?   

                                                 text  
7   Yes, we will keep all the materials after the ...  
0   The purpose of this document is to capture fre...  
1   GitHub - DataTalksClub data-engineering-zoomca...  
34  Star the repo! Share it with friends if you fi...  
4   You can start by installing and setting up all...

Putting all together


In [ ]:
class TextSearch:
    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient="records")

Searching


In [ ]:
index = TextSearch(text_fields=["section", "question", "text"])
index.fit(documents)

index.search(
    query="I just signed up. Is it too late to join the course?",
    n_results=5,
    boost={"question": 3.0},
    filters={"course": "data-engineering-zoomcamp"},
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineerin

## Vector Search


In [ ]:
X = matrices["text"]
cv = vectorizers["text"]

svd = TruncatedSVD(n_components=16)
X_emb = svd.fit_transform(X)

X_emb.shape

(948, 16)

Dense representation of documents (embeddings)


In [ ]:
X_emb[0]

array([ 0.09652939, -0.08220536, -0.10269583, -0.07888492,  0.0688845 ,
       -0.06010652,  0.01896283, -0.15131328, -0.22164436, -0.27420628,
        0.12057112,  0.06016185, -0.10346335,  0.09990854,  0.03095138,
       -0.01011112])

In [ ]:
query = "I just signed up. Is it too late to join the course?"

Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.05790068, -0.03850882, -0.05679924, -0.0280689 ,  0.04099817,
       -0.06254927,  0.00922403, -0.09846986, -0.15605146, -0.18274481,
        0.09566324,  0.06353763, -0.07463788,  0.05534739,  0.03201764,
       -0.01498711])

In [ ]:
np.dot(X_emb[0], Q_emb[0])

np.float64(0.15290943169419263)

In [ ]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
df.loc[idx]

course                           section  \
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
0    data-engineering-zoomcamp  General course-related questions   
449  machine-learning-zoomcamp  General course-related questions   
451  machine-learning-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   
2    data-engineering-zoomcamp  General course-related questions   
436  machine-learning-zoomcamp  General course-related questions   
13   data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   
15   data-engineering-zoomcamp  General course-related questions   

                                              question  \
764  What If I submitted only two projects and fail...   
0                 Course - When will the course start?   
449  The course has already started. Can I still jo...   
451      Can I submit the homework after the due date?   
814  What if my answer is not exactly the same as t...   
2    Course - Can I still join the course after the...   
436                      Is it going to be live? When?   
13   Office Hours - I can’t attend the “Office hour...   
7    Course - Can I follow the course after it fini...   
15   Homework - Are late submissions of homework al...   

                                                  text  
764  If you have submitted two projects (and peer-r...  
0    The purpose of this document is to capture fre...  
449  Yes, you can. You won’t be able to submit some...  
451  No, it’s not possible. The form is closed afte...  
814  Please choose the closest one to your answer. ...  
2    Yes, even if you don't register, you're still ...  
436  The course videos are pre-recorded, you can st...  
13   Yes! Every “Office Hours” will be recorded and...  
7    Yes, we will keep all the materials after the ...  
15   No, late submissions are not allowed. But if t...

In [ ]:
nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.27529579, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [ ]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]

array([0.        , 0.00224623, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.1818919 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0017897 ,
       0.        ])

In [26]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
df.loc[idx]

course                           section  \
2    data-engineering-zoomcamp  General course-related questions   
0    data-engineering-zoomcamp  General course-related questions   
436  machine-learning-zoomcamp  General course-related questions   
449  machine-learning-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
451  machine-learning-zoomcamp  General course-related questions   
437  machine-learning-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   

                                              question  \
2    Course - Can I still join the course after the...   
0                 Course - When will the course start?   
436                      Is it going to be live? When?   
449  The course has already started. Can I still jo...   
814  What if my answer is not exactly the same as t...   
764  What If I submitted only two projects and fail...   
451      Can I submit the homework after the due date?   
437                          What if I miss a session?   
11   Certificate - Can I follow the course in a sel...   
7    Course - Can I follow the course after it fini...   

                                                  text  
2    Yes, even if you don't register, you're still ...  
0    The purpose of this document is to capture fre...  
436  The course videos are pre-recorded, you can st...  
449  Yes, you can. You won’t be able to submit some...  
814  Please choose the closest one to your answer. ...  
764  If you have submitted two projects (and peer-r...  
451  No, it’s not possible. The form is closed afte...  
437  Everything is recorded, so you won’t miss anyt...  
11   No, you can only get a certificate if you fini...  
7    Yes, we will keep all the materials after the ...