In [63]:
!uv pip install numpy==2.3.0
# %pip install numpy==2.3.0

Audited 1 package in 11ms


In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
print(array1)
print(type(array1))
print(array1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
array2 = np.array([1, 2, 3, 4, 5])
array2.reshape(1, 5)  # 1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
array3 = np.array([[1, 2, 3, 4, 5]])
array3.shape

(1, 5)

In [ ]:
array4 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(array4)
print(array4.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
# 0 - 10, from 2 to 2
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3, 4))  # 3 rows, 4 columns of number one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## entity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Array attributes
array5 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array: {array5}\n")
print(f"(Rows, Columns): {array5.shape}")
print(f"Array number of dimensions: {array5.ndim}")
print(f"Array size: {array5.size}")
print(f"Data type: {array5.dtype}")
print(f"Item size (in bytes): {array5.itemsize}")

Array: [[1 2 3]
 [4 5 6]]

(Rows, Columns): (2, 3)
Array number of dimensions: 2
Array size: 6
Data type: int64
Item size (in bytes): 8


In [ ]:
# Vectorized operations
array6 = np.array([1, 2, 3, 4, 5])
array7 = np.array([10, 20, 30, 40, 50])

print(f"Addition: {array6 + array7}")
print(f"Subtraction: {array6 - array7}")
print(f"Multiplication: {array6 * array7}")
print(f"Division: {array6 / array7}")

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
# Universal Functions
array8 = np.array([2, 3, 4, 5, 6])

print(f"Square root: {np.sqrt(array8)}")
print(f"Exponential: {np.exp(array8)}")
print(f"Sine: {np.sin(array8)}")
print(f"Natural log: {np.log(array8)}")

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
# Array slicing and indexing
array9 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])