In [1]:
%pip install numpy

In [2]:
import numpy as np

In [10]:
array1 = np.array([1, 2, 3, 4, 5])
print(array1)
print(type(array1))
print(array1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [13]:
array2 = np.array([1, 2, 3, 4, 5])
array2.reshape(1, 5) # 1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [14]:
array3 = np.array([[1, 2, 3, 4, 5]])
array3.shape

(1, 5)

In [17]:
array4 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(array4)
print(array4.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [20]:
# 0 - 10, from 2 to 2
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [23]:
np.ones((3, 4)) # 3 rows, 4 columns of number one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
## entity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])